"""add_status_field_to_todos

Revision ID: 3350dd7ab8c2
Revises: 5e9c633d21a9
Create Date: 2025-07-29 11:12:55.407347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3350dd7ab8c2'
down_revision: Union[str, None] = '5e9c633d21a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
