"""add_logging_and_performance_improvements

Revision ID: 5e9c633d21a9
Revises: 9affd570188f
Create Date: 2025-07-29 01:39:08.425567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9c633d21a9'
down_revision: Union[str, None] = '9affd570188f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # todo_assignments 테이블이 이미 존재하므로 생성하지 않음
    # op.create_table('todo_assignments', ...)
    
    # SQLite에서는 ALTER COLUMN TYPE을 지원하지 않으므로 테이블을 다시 생성
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_email_verified',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Boolean(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('is_email_verified',
                   existing_type=sa.Boolean(),
                   type_=sa.VARCHAR(),
                   existing_nullable=True)
    # ### end Alembic commands ###
