"""extend_roles_to_six_levels

Revision ID: extend_roles_migration
Revises: 3350dd7ab8c2
Create Date: 2025-01-27 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'extend_roles_migration'
down_revision: Union[str, None] = '3350dd7ab8c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 기존 member 역할을 editor로 변경하는 데이터 마이그레이션
    op.execute("UPDATE team_members SET role = 'editor' WHERE role = 'member'")
    
    # 새로운 역할들에 대한 설명을 추가할 수 있는 주석
    # OWNER: 소유자 (모든 권한)
    # ADMIN: 관리자 (거의 모든 권한)
    # MANAGER: 매니저 (팀 관리 + 콘텐츠 관리)
    # EDITOR: 편집자 (콘텐츠 생성/수정)
    # VIEWER: 조회자 (읽기 전용)
    # GUEST: 게스트 (제한적 접근)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # editor 역할을 다시 member로 되돌리는 데이터 마이그레이션
    op.execute("UPDATE team_members SET role = 'member' WHERE role = 'editor'")
    
    # ### end Alembic commands ### 